name: unit-test
on: push
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Install Commands
      run: |
        go install github.com/joho/godotenv/cmd/godotenv@latest
    - name: Install Dependencies
      run: go get ./...
    - name: Test
      run: godotenv -f ./.env go test -timeout 120s ./...